quizzy project files/Models/Buisness_Layer/teacher/teacherBL.cs
using Quizzy.Models.Buisness_Models;
using Quizzy.Models.Data_Layer.student;
using Quizzy.Models.Data_Layer.subjects;
using Quizzy.Models.Data_Layer.teacher;
using System.Data;

namespace Quizzy.Models.Buisness_Layer.teacher
{
    public class teacherBL
    {
        public static Teacher getData(string id )
        {
            teacherDL teacherDL = new teacherDL();
            Teacher model = new Teacher();
            model = teacherDL.getTeac( id );
            return model;
        }

        public DataTable getSub(Teacher t)
        {
            getSubject getSubject = new getSubject();
            DataTable table = getSubject.getSub(t.teachID);
            return table;   
        }

        public static DataTable annnounce(string id)
        {
            return teacherDL.announcement(id);
        }
        public static DataTable statsTotalstu(string id)
        {
            return teacherDL.statsTotalStu(id);
        }

        public static DataTable statsComplete(string id)
        {
            return teacherDL.statsCompQuiz(id);
        }
        public static DataTable statsUpcomming(string id)
        {
            return teacherDL.statsUpcomingQuiz(id);
        }
        public static DataTable statsAvg(string id)
        {
            return teacherDL.statsAggregate(id);
        }
    }
}

quizzy project files/Models/Buisness_Models/announcements.cs
namespace Quizzy.Models.Buisness_Models
{
    public class Announcements
    {
        public string subject { get; set; }
        public string body { get; set; }
    }
}

quizzy project files/Models/Data_Layer/teacher/teacherDL.cs
using DBHelper;
using Quizzy.Models.Buisness_Layer.subjects;
using Quizzy.Models.Buisness_Models;
using System.Data;

namespace Quizzy.Models.Data_Layer.teacher
{
    public class teacherDL
    {
        public Buisness_Models.Teacher getTeac(string id)
        {
            string query = $"select teacherID,first_name,last_name,email from teachers where teacherID = {id}";
            DataTable dt = DatabaseHelper.Instance.GetData(query);

            Teacher t= new Teacher();
            t.teachID = id;
            t.first_name = dt.Rows[0]["first_name"].ToString();
            t.last_name = dt.Rows[0]["last_name"].ToString();
            t.email = dt.Rows[0]["email"].ToString();

            return t;
        }

        public static DataTable announcement(string id)
        {
            string query = $"select s.first_name,s.last_name,s.email from enrollments e join students  s on s.studentID = e.studentID where subjectID ={id} and status = true";

            return DatabaseHelper.Instance.GetData(query);
        }



        public static DataTable statsTotalStu(string id)
        {
            string query = $"select count(studentID) as total_stu from enrollments where subjectID = {id} and status=true ";
            return DatabaseHelper.Instance.GetData(query);
        }
        public static DataTable statsCompQuiz(string id)
        {
            string query = $"select count(quizID) as quizes from quiz q join subjects s on s.subjectID=q.subjectID where s.subjectID = {id} and q.is_asssign=true";
            return DatabaseHelper.Instance.GetData(query);
        }
        public static DataTable statsUpcomingQuiz(string id)
        {
            string query = $"select count(quizID) as quizes from quiz q join subjects s on s.subjectID=q.subjectID where s.subjectID = {id} and q.is_asssign=false";
            return DatabaseHelper.Instance.GetData(query);
        }

        public static DataTable statsAggregate(string id)
        {
            string query = $"select ((sum(mcq_marks)+sum(shq_marks))/sum(total_marks))*100 as aggregate from results r join quiz q on q.quizID=r.quizID where subjectID={id} ";
            return DatabaseHelper.Instance.GetData(query);
        }
    }
}

quizzy project files/Controllers/teacher/teacherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using MimeKit;
using Quizzy.Helpers;
using Quizzy.Models.Buisness_Layer.student;
using Quizzy.Models.Buisness_Layer.subjects;
using Quizzy.Models.Buisness_Layer.teacher;
using Quizzy.Models.Buisness_Models;
using Quizzy.Models.Data_Layer.subjects;
using System.Data;

namespace Quizzy.Controllers.teacher
{
    public class teacherController : Controller
    {
        Teacher teacher = new Teacher();

        //there is an issue in saving the session of the teacher
        public IActionResult home()
        {

            var teacher = HttpContext.Session.GetObject<Teacher>("teacherObj");
            var subject = HttpContext.Session.GetObject<subject_model>("subjectObj");


            if (teacher == null || subject == null)
            {

                TempData["log"] = "Session Expired";

                return RedirectToAction("index", "login");
            }


            DataTable enrolled = teacherBL.statsTotalstu(subject.subjectID);
            string enroll = enrolled.Rows[0]["total_stu"].ToString();

            DataTable compquiz = teacherBL.statsComplete(subject.subjectID);
            string completequiz = compquiz.Rows[0]["quizes"].ToString();

            DataTable upcomming = teacherBL.statsUpcomming(subject.subjectID);
            string upcomm = upcomming.Rows[0]["quizes"].ToString();

            DataTable aggregate = teacherBL.statsAvg(subject.subjectID);

            string agregate;
            if (aggregate == null || aggregate.Rows.Count == 0)
            {
                agregate = "0.00";
            }
            else
            {
                agregate = aggregate.Rows[0]["aggregate"].ToString();
            }
            
            ViewBag.enroll = enroll;
            ViewBag.compquiz = completequiz;
            ViewBag.upcomming = upcomm;
            ViewBag.aggregate = agregate;



            viewModel view = new viewModel
            {
                Teacher = teacher,
                Subject = subject
            };
            return View("mainpage_teacher", view);
        }
        public IActionResult main()
        {
            string id = HttpContext.Session.GetString("teacId");
            Console.WriteLine(id);
            if (string.IsNullOrEmpty(id))
            {
                if (Request.Cookies["teacId"] != null)
                {

                    id = Request.Cookies["teacId"];
                    HttpContext.Session.SetString("teacId", id); // restore session
                    Console.WriteLine($"an old session of teacher with id {id} was found ");
                }
                else
                {
                    TempData["log"] = "Session not found";

                    return RedirectToAction("index", "login");
                }
            }

            teacher = teacherBL.getData(id);
            HttpContext.Session.SetObject("teacherObj", teacher);
            return RedirectToAction("subjectSelect");
        }
        [HttpGet]
        public IActionResult subjectSelect()
        {
            var teacher = HttpContext.Session.GetObject<Teacher>("teacherObj");
            if (teacher == null)
            {
                TempData["log"] = "Session not found";

                return RedirectToAction("index", "login");
            }
            DataTable dt = getSubject.getSub(teacher.teachID);
            ViewBag.Subjects = dt;
            return View("selectSub");
        }


        [HttpPost]
        public IActionResult subjectSelect(string selectedSubjectId)
        {
            // Store in session
            HttpContext.Session.SetString("subjectID", selectedSubjectId);


            subject_model model = new subject_model();
            model = subjectBL.getSubfromid(selectedSubjectId);
            HttpContext.Session.SetObject("subjectObj", model);

            return RedirectToAction("home");
        }

        public IActionResult logOut()
        {

            var teacher = HttpContext.Session.GetObject<Teacher>("teacherObj");
            if (teacher == null)
            {
                TempData["log"] = "Session not found";

                return RedirectToAction("index", "login");
            }

            Console.WriteLine($"user with name {teacher.first_name} {teacher.last_name} is loging out");
            HttpContext.Session.Clear();

            teacher = null;
            if (Request.Cookies["teacId"] != null)
            {
                Response.Cookies.Delete("teacId");
            }

            TempData["check"] = "Logged Out Successfully";
            return RedirectToAction("index", "login");


        }

        public IActionResult studentManage()
        {
            var teacher = HttpContext.Session.GetObject<Teacher>("teacherObj");
            var subject = HttpContext.Session.GetObject<subject_model>("subjectObj");

            if (teacher == null || subject==null)
            {
                TempData["log"] = "Session not found";

                return RedirectToAction("index", "login");
            }

            Console.WriteLine($"{subject.name}");

            DataTable dt1 = StudentBL.viewReq(subject.subjectID);

            ViewBag.subject = subject;
            ViewBag.teacher = teacher;
            ViewBag.student = dt1;
            return View("studentManage");
        }
        [HttpPost]
        public IActionResult assign(string studentID)
        {
            var subject = HttpContext.Session.GetObject<subject_model>("subjectObj");

            if (subject == null)
            {
                TempData["log"] = "Session not found";

                return RedirectToAction("index", "login");
            }

            Enrollment e = new Enrollment();
            e.stuID= studentID;
            e.courseID = subject.subjectID;
            e.status = true;

            if (StudentBL.updateAssign(e))
            {
                TempData["Check"] = "Student enrolled in the course successfully";

                string serverAddress = $"{Request.Scheme}://{Request.Host}";
                string loginUrl = $"{serverAddress}/login/index";
                var teacher = HttpContext.Session.GetObject<Teacher>("teacherObj");
                Student stu = StudentBL.getData(studentID);

                var message = new MimeMessage();
                message.From.Add(new MailboxAddress("Quizzy - Modern Quiz System", "mrayyan403@gmail.com"));
                message.To.Add(new MailboxAddress(stu.first_name + " " + stu.last_name, stu.email));
                message.Subject = $"{subject.name} ({subject.code}) - Enrollment Request Accepeted";

                message.Body = new TextPart(MimeKit.Text.TextFormat.Html)
                {
                    Text = $@"
                               <html>
                                 <body style='font-family: Arial, sans-serif; background-color: white; color: #1B3D1B; padding: 30px;'>
                                     <div style='background-color: #E6F4EA; border-radius: 10px; padding: 30px; max-width: 600px; margin: auto;'>
                                         <h2 style='color: #2E8B57;'>Enrollment Request Approved!</h2>

                                         <p>Dear <h1 style=""margin: 0;"">{stu.first_name} {stu.last_name}</h1></p>

                                         <h2 style='color: #2E8B57;'>Congratulations!</h2>
                                         <p>Your request to enroll in the course <b>{subject.code} - {subject.name}</b> has been <strong>approved</strong> by the course instructor <strong>Prof. {teacher.first_name} {teacher.last_name}</strong>.</p>
                                         <p>Your roll number is <b>{stu.addmission_year}-{stu.dept}-{stu.roll_num}</b>, and you are now officially part of the <b>{stu.dept}</b> department.</p>

                                         <p>You can now access course materials, assignments, and updates through your Quizzy dashboard.</p>

                                         <div style='text-align: center; margin-top: 20px;'>
                                             <a href='{loginUrl}' style='background-color: #2E8B57; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-size: 16px;'>Go to Dashboard</a>
                                         </div>

                                         <div style='margin-top: 40px; font-size: 12px; color: #777; text-align: center;'>
                                             <footer style='font-size: 12px; color: #555;'>Happy Learning!</footer>
                                             &copy; 2025 Quizzy. All rights reserved.
                                         </div>
                                     </div>
                                 </body>
                                </html>

                               
                                    "

                };
                try
                {
                    using (var client = new MailKit.Net.Smtp.SmtpClient())
                    {
                        client.Connect("smtp.gmail.com", 587, MailKit.Security.SecureSocketOptions.StartTls);
                        client.Authenticate("mrayyan403@gmail.com", "yuax ekty ofav lkvj"); // your app password
                        client.Send(message);
                        client.Disconnect(true);
                    }
                }
                catch (Exception ex)
                {
                    TempData["log"] = "Internet not connected";
                    Console.WriteLine("internet issue");

                }



            }
            else
            {
                TempData["log"] = "Error in enrolling student";
            }

            return RedirectToAction("studentManage");


        }

        public IActionResult unassign(string studentID)
        {
            var subject = HttpContext.Session.GetObject<subject_model>("subjectObj");

quizzy project files/Views/teacher/addNewSubject.cshtml
@model Quizzy.Models.Buisness_Models.subject_model

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Subject- Quizzy</title>
    <link rel="stylesheet" href="~/css/login_page.css">
    <script type="text/javascript" src="~/js/login.js" defer></script>
</head>
<body>
    <div class="wrapper">
        <h1>Add Subject</h1>
        <p id="error-message"></p>
        <p>Please add the details of your subject</p>
        @if (TempData["Check"] != null)
        {
            <div style="color: #07fc03; font-size: 16px; text-align: center;">
                @TempData["Check"]
            </div>
        }
        @if (TempData["log"] != null)
        {
            <div style="color: red; font-size: 16px; text-align: center;">
                @TempData["log"]
            </div>
        }
        <form id="form" method="post">
            <div>
                <label for="email-input">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24">
                        <path d="M120-200q-24 0-42-18t-18-42v-440q0-24 18-42t42-18h720q24 0 42 18t18 42v440q0 24-18 42t-42 18H120Zm360-230L140-680v440h680v-440L480-430Zm0-70 360-220H120l360 220ZM140-680v-40 480-440Z" />
                    </svg>
                </label>
                <input type="text" id="email-input" placeholder="Subject Name" asp-for="name" >
            </div>

            <div>
                <label for="password-input">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M240-80q-33 0-56.5-23.5T160-160v-400q0-33 23.5-56.5T240-640h40v-80q0-83 58.5-141.5T480-920q83 0 141.5 58.5T680-720v80h40q33 0 56.5 23.5T800-560v400q0 33-23.5 56.5T720-80H240Zm240-200q33 0 56.5-23.5T560-360q0-33-23.5-56.5T480-440q-33 0-56.5 23.5T400-360q0 33 23.5 56.5T480-280ZM360-640h240v-80q0-50-35-85t-85-35q-50 0-85 35t-35 85v80Z" /></svg>
                </label>
                <input type="text" id="password-input" placeholder="Subject Code (5 Characters)" asp-for="code" >
            </div>
            <button type="submit">Add Subject</button>
        </form>
    </div>
</body>
</html>

quizzy project files/Views/teacher/announcements.cshtml
    @{
        var teacher = ViewBag.teacher as Quizzy.Models.Buisness_Models.Teacher;
        var subject = ViewBag.subject as Quizzy.Models.Buisness_Models.subject_model;
        
    }
    @model Quizzy.Models.Buisness_Models.Announcements


<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Dashboard - Quizzy</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/mainpage_teacher.css">
</head>
<body>


    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar-container">
            <div class="navbar-brand">

                <i class="fas fa-graduation-cap brand-icon"></i>
                <h2>Quizzy</h2>
            </div>
            <div class="navbar-menu">
                <div class="user-welcome">
                    <i class="fas fa-user-circle user-icon"></i>
                    <span>Welcome, @teacher.first_name @teacher.last_name</span>
                </div>
                <a href="/teacher/logOut" class="btn-logout"><i class="fas fa-sign-out-alt"></i> Log Out</a>
            </div>
        </div>
    </nav>
    <a href="/teacher/home" class="btn-go-back">
        <i class="fas fa-arrow-left"></i> Go Back
    </a>
    <div class="content-wrapper">
        <div class="dashboard-header">
            <h1>Teacher Dashboard</h1>
            <div class="course-badge">
                <i class="fas fa-book-open"></i>
                <span>Current Course: @subject.code - @subject.name</span>
            </div>
        </div>
    </div>
    @if (TempData["Check"] != null)
    {
        <div style="color: #07fc03; font-size: 16px; text-align: center;">
            @TempData["Check"]
        </div>
    }
    @if (TempData["log"] != null)
    {
        <div style="color: red; font-size: 16px; text-align: center;">
            @TempData["log"]
        </div>
    }


    <!-- Announcement Form -->
    <div class="announcement-form">
        <h2>Send Announcement</h2>
        <form method="post" asp-controller="teacher" asp-action="sendAnnouncement">
            <input type="text"  asp-for="subject" placeholder="Subject" required />
            <textarea  rows="6" asp-for="body" placeholder="Enter your announcement..." required></textarea>
            <button type="submit">Send to Students</button>
        </form>
    </div>


    <div class="dashboard-footer">
        <p class="footer-message">Happy Teaching, @teacher.first_name @teacher.last_name!</p>
        <p class="copyright">&copy; 2025 Quizzy. All rights reserved.</p>
    </div>
    <!-- Sending Modal -->
    <div id="sendingModal" style="display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(255,255,255,0.8); z-index:9999; text-align:center; padding-top:200px; font-size:24px;">
        <div class="loading-spinner"></div>
        <p>Sending announcements to all the registered emails, please wait...</p>
    </div>



    <script>
        document.querySelector("form").addEventListener("submit", function (e) {
            document.getElementById("sendingModal").style.display = "block";
        });
    </script>
</body>
</html>

quizzy project files/Views/teacher/selectSub.cshtml
@model Quizzy.Models.Buisness_Models.login_models

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Select Subject - Quizzy</title>
    <link rel="stylesheet" href="~/css/login_page.css">
    <script type="text/javascript" src="~/js/login.js" defer></script>
</head>
<body>
    <div class="wrapper">
        <h1>Subjects</h1>
            <p>Select the subject you want to log in</p>

        @if (TempData["Check"] != null)
        {
            <div style="color: #07fc03; font-size: 16px; text-align: center;">
                @TempData["Check"]
            </div>
        }
        @if (TempData["log"] != null)
        {
            <div style="color: red; font-size: 16px; text-align: center;">
                @TempData["log"]
            </div>
        }
        @{
            var subjects = ViewBag.Subjects as System.Data.DataTable;
        }

        @if (subjects == null || subjects.Rows.Count == 0)
        {
            <div style="color: red; font-size: 16px; text-align: center;">
                No subjects found
            </div>
        }
        
        
        <!-- Form to select subject -->
        <form method="post" asp-action="subjectSelect">
            <div class="form-group">
                <label for="subject-select">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24">
                        <path d="M120-200q-24 0-42-18t-18-42v-440q0-24 18-42t42-18h720q24 0 42 18t18 42v440q0 24-18 42t-42 18H120Zm360-230L140-680v440h680v-440L480-430Zm0-70 360-220H120l360 220ZM140-680v-40 480-440Z" />
                    </svg>
                </label>
                <select name="selectedSubjectId" id="subject-select" class="custom-select">
                    @if (ViewBag.Subjects != null)
                    {
                        if (subjects.Rows.Count > 0)
                        {
                            foreach (System.Data.DataRow row in subjects.Rows)
                            {
                                <option value="@row["subjectId"]">@row["subject_code"]-@row["subject_name"]</option>
                            }
                        }
                        else
                        {
                           
                            <option disabled>No subjects found</option>
                            
                        }
                    }
                    else
                    {

                        
                        <option disabled>No subjects found</option>
                       
                    }

                </select>
            </div>

            <button type="submit" class="btn-submit">Open Subject</button>
        </form>

        <!-- Button to go to the page to create a new subject -->
        <p>No Subject Found? <a href="/subject/addSubject">Create a new subject</a></p>

    </div>

</body>
</html>

<style>
    .custom-select {
        width: 100%;
        height: 60px;
        padding: 1em;
        font: inherit;
        border-radius: 10px;
        border: 2px solid var(--input-color);
        background-color: var(--input-color);
        transition: 150ms ease;
    }

        .custom-select:focus {
            outline: none;
            border-color: var(--accent-color);
            background-color: #fff;
        }

        .custom-select:hover {
            border-color: var(--accent-color);
        }

    .btn-submit {
        margin-top: 10px;
        border: none;
        border-radius: 1000px;
        padding: .85em 4em;
        background-color: var(--accent-color);
        color: var(--base-color);
        font: inherit;
        font-weight: 600;
        text-transform: uppercase;
        cursor: pointer;
        transition: 150ms ease;
    }

        .btn-submit:hover {
            background-color: var(--text-color);
        }

        .btn-submit:focus {
            outline: none;
            background-color: var(--text-color);
        }

    .btn-create-subject {
        display: inline-block;
        margin-top: 20px;
        padding: .85em 4em;
        background-color: var(--accent-color);
        color: var(--base-color);
        font: inherit;
        font-weight: 600;
        text-transform: uppercase;
        text-decoration: none;
        border-radius: 1000px;
        transition: 150ms ease;
    }

        .btn-create-subject:hover {
            background-color: var(--text-color);
        }

        .btn-create-subject:focus {
            outline: none;
            background-color: var(--text-color);
        }
</style>

quizzy project files/Views/teacher/studentManage.cshtml
    @{
        var teacher = ViewBag.teacher as Quizzy.Models.Buisness_Models.Teacher;
        var subject = ViewBag.subject as Quizzy.Models.Buisness_Models.subject_model;
        var studentsDt = ViewBag.student as System.Data.DataTable;


    }


    <!DOCTYPE html>
    <html lang="en">
    <head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Manage Students - Quizzy</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="~/css/mainpage_teacher.css">
        </head>
    <body>


    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar-container">
            <div class="navbar-brand">
                
                <i class="fas fa-graduation-cap brand-icon"></i>
                <h2>Quizzy</h2>
            </div>
            <div class="navbar-menu">
                <div class="user-welcome">
                    <i class="fas fa-user-circle user-icon"></i>
                    <span>Welcome, @teacher.first_name @teacher.last_name</span>
                </div>
                <a href="/teacher/logOut" class="btn-logout"><i class="fas fa-sign-out-alt"></i> Log Out</a>
            </div>
        </div>
    </nav>
    <a href="/teacher/home" class="btn-go-back">
        <i class="fas fa-arrow-left"></i> Go Back
    </a>
        <div class="content-wrapper">
            <div class="dashboard-header">
                <h1>Teacher Dashboard</h1>
                <div class="course-badge">
                    <i class="fas fa-book-open"></i>
                

                    <span>Current Course: @subject.code - @subject.name</span>
                </div>
       </div>
       </div>
    @if (TempData["Check"] != null)
    {
        <div style="color: #07fc03; font-size: 16px; text-align: center;">
            @TempData["Check"]
        </div>
    }
    @if (TempData["log"] != null)
    {
        <div style="color: red; font-size: 16px; text-align: center;">
            @TempData["log"]
        </div>
    }

    <!-- Student Assignment Section -->
    <div class="student-assignments">
        <div class="section-header">
            <h2>Students Management</h2>
        </div>

        @if (studentsDt != null && studentsDt.Rows.Count > 0)
        {
            <table class="student-assignment-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Roll Number</th>
                        <th>Department</th>
                        <th>Enrollments</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (System.Data.DataRow row in studentsDt.Rows)
                    {
                        var isAssigned = Convert.ToBoolean(row["status"]);
                        <tr>
                            <td>@row["first_name"] @row["last_name"]</td>
                            <td>@row["addmission_year"]-@row["dept"]-@row["roll_num"]</td>
                            <td>@row["dept"]</td>
                            <td>
                                <form method="post" asp-controller="teacher" asp-action="assign" style="display: inline;">
                                    <input type="hidden" name="studentId" value="@row["studentID"]" />
                                    <button type="submit" class="btn-enroll" @(isAssigned ? "disabled" : "")>
                                        <i class="fas fa-plus"></i> Enroll
                                    </button>
                                </form>

                                <form method="post" asp-controller="teacher" asp-action="unassign" style="display: inline;">
                                    <input type="hidden" name="studentId" value="@row["studentID"]" />
                                    <button type="submit" class="btn-unenroll" @(!isAssigned ? "disabled" : "")>
                                        <i class="fas fa-minus"></i> Unenroll
                                    </button>

                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="empty-state">
                <i class="fas fa-user-times"></i>
                <div class="empty-message">No students found.</div>
            </div>
        }
                <!-- Footer Section -->
                <div class="dashboard-footer">
                    <p class="footer-message">Happy Teaching, @teacher.first_name @teacher.last_name!</p>
                    <p class="copyright">&copy; 2025 Quizzy. All rights reserved.</p>
                </div>
    </div>
    </body>
    </html>