quizzy project files/Models/Buisness_Layer/student/StudentBL.cs
using Microsoft.AspNetCore.StaticFiles;
using Quizzy.Models.Buisness_Models;
using Quizzy.Models.Data_Layer.quiz;
using Quizzy.Models.Data_Layer.student;
using Quizzy.Models.DataLayer_Models;
using System.Data;

namespace Quizzy.Models.Buisness_Layer.student
{
    public class StudentBL
    {
        public static Models.Buisness_Models.Student getData(string id)
        {   
            studentDL model = new studentDL();
            Student student = new Student();
            student = model.getStu(id);

            return student;

        }
        public static DataTable getStuCourses(string id)
        {
            DataTable dt = studentDL.getStuSub(id);
            return dt;
        }
        public static DataTable getAllStuCourses()
        {
            DataTable dt = studentDL.getAllStuSub();
            return dt;
        }

        public static bool stuEnroll(Enrollment e)
        {
            enrollModel em = new enrollModel(); 
            em.status = e.status;
            int stuID;
            bool flag = int.TryParse(e.stuID, out stuID);
            int courseId;
            bool flag2 = int.TryParse(e.courseID, out courseId);

            if (!flag2 || !flag) 
            {
                return false;
            }
            em.stuID = stuID;
            em.courseID = courseId;
            return studentDL.enrollStu(em);
            
        }
        public static bool CheckIfEnrolled(Enrollment e)
        {
            DataTable dt = studentDL.checkIfEnrolled(e);
            if (dt == null || dt.Rows.Count==0)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        public static subject_model getSub(string id)
        {
            subject_model subjectModel = new subject_model();
            subjectModel = studentDL.getSubject(id);

            return subjectModel;
        }
        public static Teacher getTec(string id)
        {
            Teacher t = new Teacher();
            t= studentDL.getTeacher(id);
            return t;
        }

        public static DataTable viewReq(string id)
        {
            DataTable dt = studentDL.viewReq(id);
            return dt;
        }

        public static bool updateAssign(Enrollment e)
        {
            return studentDL.updateEnroll(e);
        }
        public static bool deleteAssign(Enrollment e)
        {
            return studentDL.unEnroll(e);
        }
        public static DataTable statsEnroll(string id)
        {
            return studentDL.statsEnroll(id);
        }
        public static DataTable statsComplete(string id)
        {
            return studentDL.statsCompQuiz(id);
        }
        public static DataTable statsUpcomming(string id)
        {
            return studentDL.statsUpcomingQuiz(id);
        }
        public static DataTable statsAvg(string id)
        {
            return studentDL.statsAggregate(id);
        }
    }
}

quizzy project files/Controllers/student/studentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Primitives;
using MimeKit;
using Mysqlx.Crud;
using Quizzy.Helpers;
using Quizzy.Models.Buisness_Layer.quiz;
using Quizzy.Models.Buisness_Layer.student;
using Quizzy.Models.Buisness_Layer.subjects;
using Quizzy.Models.Buisness_Models;
using System.Data;
using System.Security.Cryptography.X509Certificates;

namespace Quizzy.Controllers.student
{
    public class studentController : Controller
    {
        Student stu = new Student();

        public IActionResult availableQuizes()
        {
            var stu = HttpContext.Session.GetObject<Student>("StudentObj");

            if (stu == null)
            {
                TempData["log"] = "Session not found";
                return RedirectToAction("index", "login");
            }

            DataTable dt = stu_quizBL.getopenquiz();
            ViewBag.quiz = dt;

            Console.WriteLine($"open quizes section has been opened by the student with name {stu.first_name} {stu.last_name} ");

            ViewBag.stu = stu;
            return View("seeOpenQuiz");
        }
        public IActionResult main()
        {
            string id = HttpContext.Session.GetString("UserId");
            Console.WriteLine(id);

            if (string.IsNullOrEmpty(id))
                {
                    if (Request.Cookies["UserId"] != null)
                    {
                        id = Request.Cookies["UserId"];
                        HttpContext.Session.SetString("UserId", id); // restore session
                        Console.WriteLine($"an old session of student with id {id} was found ");
                    }
                    else
                    {
                        TempData["log"] = "Session not found";
                        return RedirectToAction("index", "login");
                    }
                }
           
            stu = StudentBL.getData(id);
            HttpContext.Session.SetObject("StudentObj", stu);
            return RedirectToAction("enrolledCourse");
        }

        public IActionResult logOut()
        {
            var stu = HttpContext.Session.GetObject<Student>("StudentObj");

            if (stu == null)
            {
                TempData["log"] = "Session not found";
                return RedirectToAction("index", "login");
            }
            Console.WriteLine($"user with name {stu.first_name} {stu.last_name} is loging out");
            HttpContext.Session.Clear();

            stu = null;
            if (Request.Cookies["UserId"] != null)
            {
                Response.Cookies.Delete("UserId");
            }

            TempData["check"] = "Logged Out Successfully";

            return RedirectToAction("index", "login");
        }

        [HttpGet]

        public IActionResult enrolledCourse()
        {
            var stu = HttpContext.Session.GetObject<Student>("StudentObj");

            if (stu == null)
            {
                TempData["log"] = "Session not found";

                return RedirectToAction("index", "login");
            }
            DataTable dt = StudentBL.getStuCourses(stu.stuID);

            DataTable enrolled = StudentBL.statsEnroll(stu.stuID);
            string enroll = enrolled.Rows[0]["enroll"].ToString();

            DataTable compquiz = StudentBL.statsComplete(stu.stuID);
            string completequiz = compquiz.Rows[0]["comp_quiz"].ToString();

            DataTable upcomming = StudentBL.statsUpcomming(stu.stuID);
            string upcomm = upcomming.Rows[0]["upcoming"].ToString();

            DataTable aggregate = StudentBL.statsAvg(stu.stuID);

            string agregate;
            if (aggregate == null || aggregate.Rows.Count == 0)
            {
                agregate = "0.00";
            }
            else
            {
                agregate = aggregate.Rows[0]["agrregate"].ToString();
            }
            ViewBag.enroll = enroll;
            ViewBag.compquiz = completequiz;
            ViewBag.upcomming = upcomm;
            ViewBag.aggregate = agregate;

            ViewBag.Enrolled = dt;
            ViewBag.stu = stu;

            return View("mainPage_student");

        }

        [HttpGet]
        public IActionResult availableCourse()
        {
            var stu = HttpContext.Session.GetObject<Student>("StudentObj");
            if (stu==null)
            {
                TempData["log"] = "Session not found";

                return RedirectToAction("index", "login");
            }
            DataTable dt = StudentBL.getAllStuCourses();

            ViewBag.Courses = dt;
            ViewBag.stu = stu;

            return View("viewAllCourses");
        }

        [HttpPost]

        public IActionResult Enroll(string courseId)
        {
            var stu = HttpContext.Session.GetObject<Student>("StudentObj");
            Enrollment e = new Enrollment();
            e.stuID = stu.stuID;
            e.courseID = courseId;
            e.status = false;
            if (StudentBL.CheckIfEnrolled(e))
            {
                bool flag = StudentBL.stuEnroll(e);

                if (!flag)
                {
                    TempData["Check"] = "Error in enrollment";
                }
                else
                {
                    TempData["log"] = "Enrollment pending!";

                    Teacher teacher = new Teacher();
                    subject_model sub = new subject_model();
                    sub = StudentBL.getSub(courseId);
                    teacher = StudentBL.getTec(sub.teacherID);
                    string serverAddress = $"{Request.Scheme}://{Request.Host}";
                    string loginUrl = $"{serverAddress}/login/index";

                    Console.WriteLine($"studemt with name {stu.first_name} {stu.last_name} has enrolled in the course {sub.code}-{sub.name} which is taught by {teacher.first_name} {teacher.last_name}");

                    var message = new MimeMessage();
                    message.From.Add(new MailboxAddress("Quizzy - Modern Quiz System", "mrayyan403@gmail.com"));
                    message.To.Add(new MailboxAddress(stu.first_name + " " + stu.last_name, stu.email));
                    message.Subject = "Subject Enrollment Pending - Quizzy";

                    message.Body = new TextPart(MimeKit.Text.TextFormat.Html)
                    {
                        Text = $@"
                                <html>
                                <body style='font-family: Arial, sans-serif; background-color: white; color: #2E2B41; padding: 30px;'>
                                    <div style='background-color: #F3F0FF; border-radius: 10px; padding: 30px; max-width: 600px; margin: auto;'>
                                        <h2 style='color: #8672FF;'>Request Sent Successfully!</h2>

                                        <p>Dear,<h1> {stu.first_name} {stu.last_name}</h1></p>

                                        <h2 style='color: #8672FF;'>Great News!</h2>
                                        <p>Your request to enroll in the course <b>{sub.code}-{sub.name}</b> has been sent to the course instructor <strong>Proff. {teacher.first_name} {teacher.last_name}</strong>.</p>
                                        <p>Your roll number is <b>{stu.addmission_year}-{stu.dept}-{stu.roll_num}</b> and you have been registered in the <b>{stu.dept}</b> Department.</p>
                                        <p>Please note that your request is currently under review by the instructor. You will receive a notification once your enrollment is accepted.</p>
                                        <p>In the meantime, feel free to explore other courses or visit your dashboard for updates.</p>
        
        
                                        <div style='text-align: center; margin-top: 20px;'>
                                            <a href='{loginUrl}' style='background-color: #8672FF; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-size: 16px;'>Login to Quizzy</a>
                                        </div>

                                        <div style='margin-top: 40px; font-size: 12px; color: #999; text-align: center;'>
                                            <footer style='font-size: 12px; color: #888;'>Happy Learning!</footer>
                                            &copy; 2025 Quizzy. All rights reserved.
                                        </div>
                                    </div>
                                </body>
                                </html>"

                    };
                    try
                    {
                        using (var client = new MailKit.Net.Smtp.SmtpClient())
                        {
                            client.Connect("smtp.gmail.com", 587, MailKit.Security.SecureSocketOptions.StartTls);
                            client.Authenticate("mrayyan403@gmail.com", "yuax ekty ofav lkvj"); // your app password
                            client.Send(message);
                            client.Disconnect(true);
                        }
                    }
                    catch (Exception ex)
                    {
                        TempData["Check"] = "Internet not connected";
                        Console.WriteLine("internet issue");
                    }

                    //to the teacher

                    var message1= new MimeMessage();
                    message1.From.Add(new MailboxAddress("Quizzy - Modern Quiz System", "mrayyan403@gmail.com"));
                    message1.To.Add(new MailboxAddress(teacher.first_name + " " + teacher.last_name, teacher.email));
                    message1.Subject = "New Enrollment Request - Quizzy";

                    message1.Body = new TextPart(MimeKit.Text.TextFormat.Html)
                    {
                        Text = $@"
                        <html>

quizzy project files/Views/student/coursePage.cshtml
@{

    var student = ViewBag.stu as Quizzy.Models.Buisness_Models.Student;
    var sub = ViewBag.sub as Quizzy.Models.Buisness_Models.subject_model;

}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@sub.code-@sub.name - Quizzy</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/studentMain.css">
    <link rel="stylesheet" href="~/css/mainpage_teacher.css">

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const imagePlaceholders = [
                {
                    element: document.querySelector('.option-card:nth-child(1) img'),
                    backgroundColor: '#E3F2FD',
                    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 100 100">
                                <rect width="100%" height="100%" fill="#E3F2FD"/>
                                <g transform="translate(20,20) scale(0.6)">
                                    <path fill="#8672FF" d="M50 5c-1.4 0-2.5 1.1-2.5 2.5v10c0 1.4 1.1 2.5 2.5 2.5s2.5-1.1 2.5-2.5v-10c0-1.4-1.1-2.5-2.5-2.5zm17.5 5h-10c-1.4 0-2.5 1.1-2.5 2.5s1.1 2.5 2.5 2.5h10c1.4 0 2.5-1.1 2.5-2.5s-1.1-2.5-2.5-2.5zm7.5 7.5h-5v-5h-5v5h-5v5h5v5h5v-5h5v-5zM65 42.5H35c-1.4 0-2.5 1.1-2.5 2.5s1.1 2.5 2.5 2.5h30c1.4 0 2.5-1.1 2.5-2.5s-1.1-2.5-2.5-2.5zm0 10H35c-1.4 0-2.5 1.1-2.5 2.5s1.1 2.5 2.5 2.5h30c1.4 0 2.5-1.1 2.5-2.5s-1.1-2.5-2.5-2.5zm0 10H35c-1.4 0-2.5 1.1-2.5 2.5s1.1 2.5 2.5 2.5h30c1.4 0 2.5-1.1 2.5-2.5s-1.1-2.5-2.5-2.5z"/>
                                    <path fill="#2E2B41" d="M82.5 15h-65C13.2 15 10 18.2 10 22.5v55c0 4.3 3.2 7.5 7.5 7.5h65c4.3 0 7.5-3.2 7.5-7.5v-55c0-4.3-3.2-7.5-7.5-7.5zm2.5 62.5c0 1.4-1.1 2.5-2.5 2.5h-65c-1.4 0-2.5-1.1-2.5-2.5v-55c0-1.4 1.1-2.5 2.5-2.5h65c1.4 0 2.5 1.1 2.5 2.5v55z"/>
                                </g>
                            </svg>`
                },
                {
                    element: document.querySelector('.option-card:nth-child(2) img'),
                    backgroundColor: '#E8F5E9',
                    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 100 100">
                                <rect width="100%" height="100%" fill="#E8F5E9"/>
                                <g transform="translate(15,15) scale(0.7)">
                                    <path fill="#8672FF" d="M77.5 15h-55c-4.1 0-7.5 3.4-7.5 7.5v55c0 4.1 3.4 7.5 7.5 7.5h55c4.1 0 7.5-3.4 7.5-7.5v-55c0-4.1-3.4-7.5-7.5-7.5zm-40 50L25 52.5l5-5 7.5 7.5 25-25 5 5-30 30z"/>
                                    <path fill="#2E2B41" d="M67.5 45c-1.4 0-2.5 1.1-2.5 2.5v2.5h-30v-2.5c0-1.4-1.1-2.5-2.5-2.5s-2.5 1.1-2.5 2.5v5c0 1.4 1.1 2.5 2.5 2.5h35c1.4 0 2.5-1.1 2.5-2.5v-5c0-1.4-1.1-2.5-2.5-2.5z"/>
                                </g>
                            </svg>`
                },
                {
                    element: document.querySelector('.option-card:nth-child(3) img'),
                    backgroundColor: '#FFF3E0',
                    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 100 100">
                                <rect width="100%" height="100%" fill="#FFF3E0"/>
                                <g transform="translate(22,20) scale(0.6)">
                                    <path fill="#8672FF" d="M45 70c-8.3 0-15-6.7-15-15s6.7-15 15-15 15 6.7 15 15-6.7 15-15 15zm0-25c-5.5 0-10 4.5-10 10s4.5 10 10 10 10-4.5 10-10-4.5-10-10-10z"/>
                                    <path fill="#2E2B41" d="M82.5 35h-15c-1.4 0-2.5-1.1-2.5-2.5v-5c0-6.9-5.6-12.5-12.5-12.5h-15c-6.9 0-12.5 5.6-12.5 12.5v5c0 1.4-1.1 2.5-2.5 2.5h-15C7.4 35 5 37.4 5 40v30c0 2.6 2.4 5 5 5h75c2.6 0 5-2.4 5-5V40c0-2.6-2.4-5-5-5zM30 27.5c0-4.1 3.4-7.5 7.5-7.5h15c4.1 0 7.5 3.4 7.5 7.5v2.5h-30v-2.5zm55 42.5c0 0 0 0 0 0H5V40h15v2.5c0 1.4 1.1 2.5 2.5 2.5h45c1.4 0 2.5-1.1 2.5-2.5V40h15v30z"/>
                                    <path fill="#8672FF" d="M75 45c-1.4 0-2.5 1.1-2.5 2.5v5c0 1.4 1.1 2.5 2.5 2.5s2.5-1.1 2.5-2.5v-5c0-1.4-1.1-2.5-2.5-2.5z"/>
                                </g>
                            </svg>`
                },
                {
                    element: document.querySelector('.option-card:nth-child(4) img'),
                    backgroundColor: '#E1F5FE',
                    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 100 100">
                                <rect width="100%" height="100%" fill="#E1F5FE"/>
                                <g transform="translate(10,20) scale(0.8)">
                                    <circle cx="50" cy="30" r="10" fill="#8672FF"/>
                                    <circle cx="25" cy="45" r="7.5" fill="#8672FF"/>
                                    <circle cx="75" cy="45" r="7.5" fill="#8672FF"/>
                                    <path fill="#2E2B41" d="M50 45c-8.3 0-15 6.7-15 15v10c0 1.4 1.1 2.5 2.5 2.5h25c1.4 0 2.5-1.1 2.5-2.5V60c0-8.3-6.7-15-15-15z"/>
                                    <path fill="#2E2B41" d="M32.5 55h-15c-1.4 0-2.5 1.1-2.5 2.5V65c0 1.4 1.1 2.5 2.5 2.5h15c1.4 0 2.5-1.1 2.5-2.5v-7.5c0-1.4-1.1-2.5-2.5-2.5z"/>
                                    <path fill="#2E2B41" d="M82.5 55h-15c-1.4 0-2.5 1.1-2.5 2.5V65c0 1.4 1.1 2.5 2.5 2.5h15c1.4 0 2.5-1.1 2.5-2.5v-7.5c0-1.4-1.1-2.5-2.5-2.5z"/>
                                </g>
                            </svg>`
                }
            ];

            // Apply the SVG images to each card
            imagePlaceholders.forEach(placeholder => {
                if (placeholder.element) {
                    placeholder.element.outerHTML = placeholder.svg;
                }
            });

            // Sample data for stats - in a real application, this would come from your backend
            const statsData = [
                { selector: '.stat-value:nth-child(1)', value: 3 },
                { selector: '.stat-value:nth-child(2)', value: 12 },
                { selector: '.stat-value:nth-child(3)', value: 28 },
                { selector: '.stat-value:nth-child(4)', value: '83%' }
            ];

            // Refresh button functionality
            document.querySelector('.refresh-btn').addEventListener('click', function () {
                this.querySelector('i').classList.add('fa-spin');
                setTimeout(() => {
                    this.querySelector('i').classList.remove('fa-spin');
                }, 1000);
            });
        });
    </script>

</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar-container">
            <div class="navbar-brand">
                <i class="fas fa-graduation-cap brand-icon"></i>
                <h2>Quizzy</h2>
            </div>
            <div class="navbar-menu">
                <div class="user-welcome">
                    <i class="fas fa-user-circle user-icon"></i>
                    <span>Welcome, @student.first_name @student.last_name </span>
                </div>
                <a href="/student/logOut" class="btn-logout"><i class="fas fa-sign-out-alt"></i> Log Out</a>
            </div>
        </div>
    </nav>

    <!-- Go Back Button -->
    <a href="/student/main" class="btn-go-back">
        <i class="fas fa-arrow-left"></i> Go Back
    </a>

    <!-- Content Wrapper -->
    <div class="content-wrapper">
        <!-- Dashboard Header -->
        <div class="dashboard-header">
            <h1>Student Dashboard</h1>
            <div class="student-badge">
                <i class="fas fa-id-card"></i>
                <span>Roll No: @student.addmission_year-@student.dept-@student.roll_num</span>
            </div>
        </div>

        <!-- TempData Messages -->
        @if (TempData["Check"] != null)
        {
            <div style="color: #07fc03; font-size: 16px; text-align: center;">
                @TempData["Check"]
            </div>
        }
        @if (TempData["log"] != null)
        {
            <div style="color: red; font-size: 16px; text-align: center;">
                @TempData["log"]
            </div>
        }

        <!-- Courses Container -->
        <div class="courses-container">
            <div class="section-header">
                <h2>@sub.code-@sub.name</h2>
            </div>
        </div>

        <!-- Options Container -->
        <div class="options-container">
            <div class="option-card">
                <div class="card-icon">
                    <img src="/api/placeholder/400/320" alt="Create Quiz" />
                    <i class="fas fa-plus-circle"></i>
                </div>
                <div class="card-content">
                    <h3>Attempt Quiz</h3>
                    <p>Attempt the quizzes assigned to you</p>
                    <a href="/quiz/showQuiz" class="btn-option">Attempt Now <i class="fas fa-arrow-right"></i></a>
                </div>
            </div>

            <div class="option-card">
                <div class="card-icon">
                    <img src="/api/placeholder/400/320" alt="Review Quizzes" />
                    <i class="fas fa-clipboard-check"></i>
                </div>
                <div class="card-content">
                    <h3>View Results</h3>
                    <p>See the result of your quizzes</p>
                    <a href="/result/showResults" class="btn-option">Check Now <i class="fas fa-arrow-right"></i></a>
                </div>
            </div>

           

            <div class="option-card">
                <div class="card-icon">
                    <img src="/api/placeholder/400/320" alt="Student Management" />
                    <i class="fas fa-users"></i>
                </div>
                <div class="card-content">
                    <h3>Attempted Quizzes</h3>
                    <p>View all the quizzes you have attempted yet</p>
                    <a href="/quiz/showAttempts" class="btn-option">See Now<i class="fas fa-arrow-right"></i></a>
                </div>
            </div>
        </div> <!-- End of Options Container -->
    </div> <!-- End of Content Wrapper -->
    <!-- Footer Section -->
    <div class="dashboard-footer">
        <p class="footer-message">Happy Learning, @student.first_name @student.last_name!</p>
        <p class="copyright">&copy; 2025 Quizzy. All rights reserved.</p>
    </div>
</body>

</html>

quizzy project files/Views/student/viewAllCourses.cshtml
@{
    var dt = ViewBag.Courses as System.Data.DataTable;
    var student = ViewBag.stu as Quizzy.Models.Buisness_Models.Student;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Dashboard - Quizzy</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/studentMain.css">
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const currentPath = window.location.pathname;
            document.querySelectorAll('.nav-list a').forEach(link => {
                if (link.getAttribute('href') === currentPath) {
                    link.classList.add('active');
                } else {
                    link.classList.remove('active');
                }
            });
        });
    </script>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar-container">
            <div class="navbar-brand">
                <i class="fas fa-graduation-cap brand-icon"></i>
                <h2>Quizzy</h2>
            </div>
            <div class="navbar-menu">
                <div class="user-welcome">
                    <i class="fas fa-user-circle user-icon"></i>
                    <span>Welcome, @student.first_name @student.last_name</span>
                </div>
                <a href="/student/logOut" class="btn-logout"><i class="fas fa-sign-out-alt"></i> Log Out</a>
            </div>
        </div>
    </nav>

    <!-- Main Navigation -->
    <nav class="main-nav">
        <div class="nav-container">
            <ul class="nav-list">
                <li><a href="/student/main"><i class="fas fa-book"></i> Enrolled Courses</a></li>
                <li><a href="/student/availableCourse"><i class="fas fa-book"></i> All Courses</a></li>
                <li><a href="/student/availableQuizes"><i class="fas fa-book"></i> Available Quizzes</a></li>
            </ul>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="content-wrapper">
        <div class="dashboard-header">
            <h1>Student Dashboard</h1>
            <div class="student-badge">
                <i class="fas fa-id-card"></i>
                <span>Roll No: @student.addmission_year-@student.dept-@student.roll_num </span>
            </div>
        </div>
        @if (TempData["Check"] != null)
        {
            <div style="color: red; font-size: 16px; text-align: center;">
                @TempData["Check"]
            </div>
        }
        <!-- Available Courses Section -->
        <div class="available-courses">
            <div class="section-header">
                <h2>Available Courses</h2>
                <a href="/student/enrolledCourse" class="view-all">View enrolled courses <i class="fas fa-arrow-right"></i></a>
            </div>

            @if (dt != null && dt.Rows.Count > 0)
            {
                <table class="available-courses-table">
                    <thead>
                        <tr>
                            <th>Course</th>
                            <th>Professor</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (System.Data.DataRow row in dt.Rows)
                        {
                            <tr>
                                <td>
                                    <div class="course-code">@row["subject_name"] - @row["subject_code"]</div>
                                </td>
                                <td>Prof. @row["first_name"] @row["last_name"]</td>
                                <td>
                                    <form asp-action="Enroll" asp-controller="student" method="post">
                                        <input type="hidden" name="courseId" value="@row["subjectID"]" />
                                        <button type="submit" class="btn-enroll"><i class="fas fa-plus"></i> Enroll</button>
                                    </form>
                                </td>
                            </tr>
                        }
                        
                    </tbody>
                </table>
            }
            else
            {
                <div class="empty-state">
                    <div class="empty-icon">
                        <i class="fas fa-globe"></i>
                    </div>
                    <div class="empty-message">No available courses to enroll in at the moment.</div>
                </div>
            }
        </div> <!-- Close available-courses div -->
    </div> <!-- Close content-wrapper div -->

    <div class="dashboard-footer">
        <p class="footer-message">Happy Learning, @student.first_name @student.last_name!</p>
        <p class="copyright">&copy; 2025 Quizzy. All rights reserved.</p>
    </div>
</body>
</html>